version: 0.2

env:
  variables:
    ENVIRONMENT: dev # Default, will be overridden by pipeline parameter

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Preparing build $ENVIRONMENT environment..."
      # Clean up any existing node_modules
      - rm -rf node_modules
      - find . -name "node_modules" -type f -delete
      # Install pnpm and ts-node
      - npm install -g pnpm
      - npm install -g ts-node
      # Install dependencies with modified flags
      - pnpm install --frozen-lockfile

  pre_build:
    commands:
      - echo "Deploying infrastructure for $ENVIRONMENT environment"
      - echo "Setting up infrastructure environment for $ENVIRONMENT environment"
      - cd infrastructure && ts-node ./lib/cli/bin/ssm-params.ts export --target=infrastructure --output && cd ..
      - echo "Loading environment variables"
      - cat infrastructure/.env
      - echo 'Provisioning infrastructure for $ENVIRONMENT environment'
      - cd infrastructure && pnpm run provision:$ENVIRONMENT && cd ..

  build:
    commands:
      - echo "Setting up data for $ENVIRONMENT environment"
      - cd infrastructure && pnpm run populate-static-data:$ENVIRONMENT && cd ..
      - echo "Generating service environment files"
      - cd infrastructure && ts-node ./lib/cli/bin/ssm-params.ts export --target=frontend --output && cd ..
      - cd infrastructure && ts-node ./lib/cli/bin/ssm-params.ts export --target=link-generator --output && cd ..
      - echo "Building frontend for $ENVIRONMENT environment"
      - cd frontend && NEXT_PUBLIC_ENVIRONMENT=$ENVIRONMENT pnpm build && cd ..
      - echo "Publishing frontend for $ENVIRONMENT environment"
      - cd infrastructure && pnpm run publish:web-app && cd ..

  post_build:
    commands:
      - echo "Invalidating CloudFront cache"
      - cd infrastructure && pnpm run invalidate:cloudfront && cd ..
      - echo "📡 Retrieving deployment URL..."
      - CLOUDFRONT_DOMAIN=$(cd infrastructure && pnpm run --silent stack-outputs:web CloudFrontDomain)
      - echo "✅ Deployment complete"
      - echo "Website is now live at: https://${CLOUDFRONT_DOMAIN}"

cache:
  paths:
    - '.pnpm-store/**/*'
