version: 0.2

env:
  variables:
    ENVIRONMENT: dev # Default, will be overridden by pipeline parameter
    PATH: '/usr/local/bin:/usr/bin:/bin:$PWD/infrastructure/lib/cli/bin'

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Preparing build $ENVIRONMENT environment..."
      # Clean up any existing node_modules
      - rm -rf node_modules
      - find . -name "node_modules" -type f -delete
      # Install pnpm and ts-node
      - npm install -g pnpm
      - npm install -g ts-node
      # Install dependencies with modified flags
      - pnpm install --frozen-lockfile

  pre_build:
    commands:
      - echo "Setting up infrastructure environment for $ENVIRONMENT environment"
      - cd infrastructure && ssm-params export --target=infrastructure --output && cd ..
      - echo "Loading environment variables"
      - cat infrastructure/.env

  build:
    commands:
      - echo "Provisioning infrastructure for $ENVIRONMENT environment"
      - cd infrastructure && npx cdk deploy --all --require-approval never && cd ..
      - echo "Setting up data for $ENVIRONMENT environment"
      - cd infrastructure && data-management populate_ddb_with_static_data --verbose && cd ..
      - echo "Generating service environment files"
      - cd infrastructure && ssm-params export --target=frontend --output && cd ..
      - cd infrastructure && ssm-params export --target=link-generator --output && cd ..
      - echo "Building frontend for $ENVIRONMENT environment"
      - cd frontend && NEXT_PUBLIC_ENVIRONMENT=$ENVIRONMENT pnpm build && cd ..
      - echo "Publishing frontend for $ENVIRONMENT environment"
      - cd infrastructure && web-app-publish && cd ..

  post_build:
    commands:
      - echo "Invalidating CloudFront cache"
      - cd infrastructure && invalidate-cloudfront-distribution && cd ..
      - echo "Retrieving deployment URL..."
      - CLOUDFRONT_DOMAIN=$(cd infrastructure && stack-outputs web CloudfrontDomain)
      - echo "Deployment complete"
      - echo "Website is now live at https://${CLOUDFRONT_DOMAIN}"

cache:
  paths:
    - '.pnpm-store/**/*'
