version: 0.2

env:
  variables:
    ENVIRONMENT: dev # Default, will be overridden by pipeline parameter
    DEV_DATA_BUCKET_NAME: portfolio-development-data
    PROD_DATA_BUCKET_NAME: portfolio-production-data

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Preparing build $ENVIRONMENT environment..."
      # Clean up any existing node_modules
      - rm -rf node_modules
      - find . -name "node_modules" -type f -delete
      # Install pnpm
      - npm install -g pnpm
      # Install dependencies with modified flags
      - pnpm install --frozen-lockfile

  pre_build:
    commands:
      - echo "Deploying infrastructure for $ENVIRONMENT environment"
      # Fetch domain name and certificate ARN from SSM if in production environment
      - |
        if [ "$ENVIRONMENT" = "prod" ]; then
          # Run script and capture both values (format: DOMAIN_NAME|CERTIFICATE_ARN)
          DOMAIN_INFO=$(node infrastructure/lib/pipeline-helpers/fetch-domain.mjs)
          
          # Parse the output to get domain name and certificate ARN
          PROD_DOMAIN_NAME=$(echo $DOMAIN_INFO | cut -d'|' -f1)
          PROD_CERTIFICATE_ARN=$(echo $DOMAIN_INFO | cut -d'|' -f2)
          
          # Export variables for use in subsequent commands
          export PROD_DOMAIN_NAME
          export PROD_CERTIFICATE_ARN
          
          echo "Domain name set to: $PROD_DOMAIN_NAME"
          echo "Certificate ARN set to: $PROD_CERTIFICATE_ARN"
        fi
      # Pass the environment variables to the CDK command
      - cd infrastructure && PROD_DOMAIN_NAME=$PROD_DOMAIN_NAME PROD_CERTIFICATE_ARN=$PROD_CERTIFICATE_ARN pnpm run deploy:$ENVIRONMENT && cd ..

  build:
    commands:
      - echo "Setting up data for $ENVIRONMENT environment"
      - node infrastructure/lib/data-management/create-bucket.mjs $ENVIRONMENT
      - node infrastructure/lib/data-management/download-static-data.mjs $ENVIRONMENT
      - echo "Updating environment variables"
      - ENVIRONMENT=$ENVIRONMENT node infrastructure/lib/data-management/update-env.mjs
      - echo "Building and uploading frontend for $ENVIRONMENT environment"
      - cd frontend && pnpm run deploy:$ENVIRONMENT && cd ..
      - echo "Deploying frontend infrastructure for $ENVIRONMENT environment"
      - cd infrastructure && pnpm run deploy:frontend:$ENVIRONMENT && cd ..

  post_build:
    commands:
      - echo "Invalidating CloudFront cache"
      # Get CloudFront distribution ID from SSM Parameter Store
      - DISTRIBUTION_ID=$(aws ssm get-parameter --name "/portfolio/${ENVIRONMENT}/WEB_CLOUDFRONT_DISTRIBUTION_ID" --region us-east-1 --query 'Parameter.Value' --output text)
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*" --region us-east-1
      # Get domain from SSM Parameter Store
      - DOMAIN=$(aws ssm get-parameter --name "/portfolio/${ENVIRONMENT}/WEB_CLOUDFRONT_DOMAIN" --region us-east-1 --query 'Parameter.Value' --output text)
      - echo "Deployment complete. Website available at https://$DOMAIN"

cache:
  paths:
    - '.pnpm-store/**/*'
