version: 0.2

env:
  variables:
    ENVIRONMENT: dev # Default, will be overridden by pipeline parameter

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g pnpm
      - pnpm install

  pre_build:
    commands:
      - echo "Setting up data for $ENVIRONMENT environment"
      - pnpm run setup:data:$ENVIRONMENT

  build:
    commands:
      - echo "Deploying infrastructure for $ENVIRONMENT environment"
      - pnpm run deploy:infra:$ENVIRONMENT
      - echo "Updating environment variables"
      - pnpm run update:env
      - echo "Deploying frontend for $ENVIRONMENT environment"
      - pnpm run deploy:frontend:$ENVIRONMENT

  post_build:
    commands:
      - echo "Invalidating CloudFront cache"
      # Get CloudFront distribution ID from SSM Parameter Store
      - DISTRIBUTION_ID=$(aws ssm get-parameter --name "/portfolio/${ENVIRONMENT}/WEB_CLOUDFRONT_DISTRIBUTION_ID" --region us-east-1 --query 'Parameter.Value' --output text)
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*" --region us-east-1
      # Get domain from SSM Parameter Store
      - DOMAIN=$(aws ssm get-parameter --name "/portfolio/${ENVIRONMENT}/WEB_CLOUDFRONT_DOMAIN" --region us-east-1 --query 'Parameter.Value' --output text)
      - echo "Deployment complete. Website available at https://$DOMAIN"

cache:
  paths:
    - 'node_modules/**/*'
    - '.pnpm-store/**/*'
