/**
 * Stack environment type mapping
 */
import { IStackEnv } from './stack-env';

// Import stack-specific environment interfaces
export interface IWebStackEnv extends IStackEnv {
  prodDomainName?: string;
  certificateArn?: string;
  awsRegionDefault: string;
}

export interface IApiStackEnv extends IStackEnv {
  dataBucketName: string;
  awsRegionDefault: string;
  // Table names will be generated by CDK
}

export interface IAIAdvocateStackEnv extends IStackEnv {
  bedrockModelId: string;
  awsRegionDefault: string;
  // Table names will be generated by CDK
}

export interface ISharedStackEnv extends IStackEnv {
  awsAdminArn: string;
  cognitoUserPoolId?: string;
}

export interface IPipelineStackEnv extends IStackEnv {
  // No additional variables needed for pipeline stack currently
}

export interface ITestStackEnv extends IStackEnv {
  baseVar?: string;
  prodVar?: string;
}

export interface ILinkGeneratorStackEnv extends IStackEnv {
  awsRegionDistrib: string;
  awsRegionDefault: string;
}

/**
 * Type mapping for stack environment inference
 */
export interface StackEnvMap {
  web: IWebStackEnv;
  api: IApiStackEnv;
  aiAdvocate: IAIAdvocateStackEnv;
  shared: ISharedStackEnv;
  pipeline: IPipelineStackEnv;
  testStack: ITestStackEnv;
  linkGenerator: ILinkGeneratorStackEnv;
}
